leftnav:
- identifier: f628f5e1-8456-8b48-44e3-26ba67a7b224
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e26a61c8-4b94-fa70-a71e-6751ad269c19
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: d581f1ec-41b4-8d63-7de7-30a0dcaaadd9
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 2bb5b4f5-59b6-0424-b61d-8b6f049d1e7c
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: c170b976-320f-9f6e-5ebf-dee2993a7d31
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 7f3b7102-ca62-84cd-9724-2560d44984c8
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: 2a3b4b56-1a0f-6d27-0195-939c76d43a28
  name: Tools
  pageRef: /pages/tools
  weight: 70
